version: '3.9'

services:
  cypress-pnpm:
    image: marciohm/cypress-pnpm
    build: .
    volumes:
      - ./Makefile:/Makefile # Copy the repo's Makefile into docker instance file system
    command: make init
